-- Define configuration for the table
config {
  type: "table", 
  description: "Table containing sales data",
  columns: {
    order_id: "Order ID",
    product_id: "Product ID",
    quantity: "Quantity",
    unit_price: "Unit Price",
    order_date: "Order Date"
  }
}

-- Define the SELECT statement to create the table
SELECT 
1 AS order_id, 
102 AS product_id,
3 AS quantity,
234.4 AS unit_price,
"2025-01-03" AS  order_date


